jobtracker/jobtracker/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include
#Add Django site authentication urls (for login, logout, password management)

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

jobtracker/main_app/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('jobs/', views.jobs_index, name='index'),
    path('jobs/results/', views.search, name='search'),
    path('jobs/<int:job_id>/', views.jobs_detail, name='detail'),
    path('jobs/jobs_create/', views.JobCreate.as_view(), name='jobs_create'),
    path('jobs/<int:pk>/update/', views.JobUpdate.as_view(), name='jobs_update'),
    path('jobs/<int:pk>/delete/', views.JobDelete.as_view(), name='jobs_delete'),
    path('jobs/<int:job_id>/add_note/', views.add_note, name='add_note'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
]

jobtracker/main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date
from django.utils import timezone



# Create your models here.

UPDATES = (
    ('u', 'Update'),
    ('!', 'Important!!!'),
    ('p', 'Phone Screen'),
    ('f', 'Follow up'),
    ('c', 'The job has been closed'),
    ('i','Interview')
)

class Job(models.Model):
    date = models.DateField('Date applied', default=timezone.now())
    company= models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    location = models.CharField(max_length=100, default='')
    comment = models.TextField(max_length=250, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
       return f"{self.company} on {self.date}"

    def get_absolute_url(self):
       return reverse('detail', kwargs={'job_id': self.id})

    class Meta:
        ordering = ['-date']

class Note(models.Model):
    date = models.DateField('Date posted')
    comment= models.TextField(max_length=250, default='')
    update = models.CharField(
        max_length=2,
        choices=UPDATES,
        default=UPDATES[0][0]    
    )
    

    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_update_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

class Resume(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    resume = models.FileField()

    job = models.ForeignKey(Job, on_delete=models.CASCADE)

jobtracker/main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Note, Job
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['date', 'comment', 'update']


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

jobtracker/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# from example.config import pagination

import uuid

from .models import Job
from .forms import NoteForm


def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
        
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid credentials - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)



# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')


# @login_required
class JobCreate(LoginRequiredMixin, CreateView):
    model = Job
    fields = ['date', 'company', 'position', 'location', 'comment']

    def form_valid(self, form):
        form.instance.user = self.request.user  # form.instance is the job
        return super().form_valid(form)


class JobUpdate(LoginRequiredMixin, UpdateView):
    model = Job
    fields = ['location', 'comment']


class JobDelete(LoginRequiredMixin, DeleteView):
    model = Job
    success_url = '/jobs/'


@login_required
def jobs_index(request):
    jobs = Job.objects.filter(user=request.user)

    paginator = Paginator(jobs, 8)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)


    return render(request, 'jobs/index.html', {'items': items })

def search(request):
    template = 'jobs/index.html'

    query = request.GET.get('q')
    #.filter(Q(company__icontains=query) is encapsulation
    results = Job.objects.filter(Q(company__icontains=query) | Q(position__icontains=query) | Q(date__icontains=query) | Q(location__icontains=query))
    pages = pagination(request, results, num=1)

    context = {
        'items': pages[0],
        'page_range': pages[1],
    }
    return render(request, template, context)

@login_required
def jobs_detail(request, job_id):
    job = Job.objects.get(id=job_id)

    note_form = NoteForm()
    return render(request, 'jobs/detail.html', {
        'job': job, 'note_form': note_form
    })

@login_required
def add_note(request, job_id):
    form = NoteForm(request.POST)
    if form.is_valid():
        new_note = form.save(commit=False)
        new_note.job_id = job_id
        new_note.save()
    return redirect('detail', job_id=job_id)

jobtracker/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About jobTracker</h1>
<hr />
<p>This is a place where you can keep track of your current job application!</p>

{% endblock %}

jobtracker/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>appliTrack</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
          crossorigin="anonymous">
 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Anton" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Bevan&family=Medula+One&display=swap" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class='navbar-fixed'>
    <nav>
      <div class="nav-wrapper">
        <a href="#" data-target="mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul>
          {% if user.is_authenticated %}
          <!-- <li><a href="/" class="left brand-logo hide-on-med-and-down">Hi, {{user.username}}</a></li> -->
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;appliTrack</a></li>
          {% else %}
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;appliTrack</a></li>
          {% endif %}
        </ul>
        
        <ul class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
          <li><a href="{% url 'jobs_create' %}" class='nav-link'>Add a new Job</a></li>
          <li><a href="{% url 'index' %}" class='nav-link'>Your jobs</a></li>
          <li><a href="{% url 'logout'%}?next={{request.path}}" class='nav-link'>Logout</a></li>
        
          {% else %}  
          
          <li><a href="{% url 'signup' %}" class='nav-link'>Sign Up</a></li>
          <li><a href="{% url 'login'%}" class='nav-link'>Login</a></li>
         
          {% endif %}
         </ul>
      </div>
    </nav>
  </header>
  <ul class="sidenav" id="mobile">
    {% if user.is_authenticated %}
    
    <li><a href="{% url 'jobs_create' %}" class='nav-link'>Add a new job</a></li>
    <li><a href="{% url 'index' %}" class='nav-link'>Your jobs</a></li>
    <li><a href="{% url 'logout' %}" class='nav-link'>Log Out</a></li>
    {% else %}
    <li><a href="{% url 'signup' %}">Sign Up</a></li>
    <li><a href="{% url 'login' %}">Log In</a></li>
    {% endif %}
  </ul>     

  <script language="javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.sidenav');
    var instances = M.Sidenav.init(elems);
  });
  </script>

  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <!-- <div class="right">All Rights Reserved, &copy; 2020 jobTracker &nbsp;</div> -->
  </footer>
</body>
</html>

jobtracker/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1 class='homeh1'>appliTrack</h1>
<p class='homep'>Create an account to keep track of all your current job applications. I was using an excel sheet to
    keep track of all my job applications, and things would get really messy. Adding notes would get confusing, entering
    the information could have been more user friendly, so I made an app where users can login, and keep great detail of
    their job search.</p>
<h5 class='homeSub'>What can users do?</h4>
    <ol>
        <li class='homeli'>Add a job to their profile. Can update company, position, location, and important notes</li>
        <li class='homeli'>Add notes, so users can see which day they have an interview, received an update, or sent a
            follow up email</li>
        <li class='homeli'>Jobs are categorized by the date that you applied</li>
    </ol>


{% endblock %}

jobtracker/main_app/templates/jobs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class='jobdetailh1'>{{job.position}} @ {{ job.company }}</h1>
  <div class="row">
  <div class="col s6">
  <div class="card">
    <div class="card-contentdetail">
      <h4 class='addUpdateh4'>Details</h4>
      <span class="card-titledetail">Applied on {{ job.date }}</span>
      <p><span class='jobDetail'>Location:</span> {{job.location}}</p>
      <p><span class='jobDetail'>Important Notes:</span> {{job.comment}}</p>
    </div>
    <div class="card-action">
        <a class='detailbtn text-blue' href="{% url 'jobs_update' job.id %}">Edit</a>
        <a class='detailbtn' href="{% url 'jobs_delete' job.id %}">Delete</a>
    </div>
  </div>

  </div>
  <div class="col s6">
    <h4 class='addUpdateh4'>Add an update</h4>
    <form action="{% url 'add_note' job.id %}" method="post">
      {% csrf_token %}
      {{ note_form.as_p }}
      <input type="submit" class="btn" value="Add Note">
    </form>
  </div>
  <div>
    
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Note</th><th>Status</th></tr>
      </thead>
      <tbody>
        {% for note in job.note_set.all %}
          <tr>
            <td class='tdbody'>{{note.date}}</td>
            <td class='tdbody'>{{note.comment}}</td>
            <td class='tdbody'>{{note.get_update_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
let dateEl = document.getElementById('id_date');
M.Datepicker.init(dateEl, {
format: 'yyyy-mm-dd',
defaultDate: new Date(),
setDefaultDate: true,
autoClose: true
});

var selectEl = document.getElementById('id_update');
M.FormSelect.init(selectEl);
</script>
{% endblock %}

jobtracker/main_app/templates/jobs/index.html
{% extends 'base.html' %}
{% block content %}



<h1 class='joblisth1'>Applied jobs</h1>

<!-- <div class='search-bar mt-sm-2 mr-2'>
  <form method='get' action="{% url 'search'%}"">
    <input type='text' class='form-control' name='q' value="{{request.GET.q}}" id='id_q' placeholder='search...'>
    <input type="submit" class="btn" value="Submit">
  </form>

</div> -->

{% for job in items %}
  <div class="card">
      <a href='{% url "detail" job.id%}' class='jobId'>
    <div class="card-content">
      <strong class='right'><p>Applied on: {{job.date}}</p></strong>
      <span class="card-title">{{ job.company }}</span>
      <p>{{ job.position }}</p>
      <p>{{job.location}}</p>
      
      <!-- <p><input type='checkbox' value={{job.cover_letter}} />Referral? {{job.cover_letter}}</p> -->
      <p class='learnMore'>Click for more info</p>
      
    </div>
    </a>
  </div>

{% endfor %}

{% if items.paginator.num_pages > 1 %}

<div class="pagination">
  {% if items.has_previous %}
  <a class='pagination-action' href="?page=1">
    <i class="fa fa-angle-double-left" aria-hidden="true"></i> 
  </a>
  <a href="?page={{ items.previous_page_number }}">
    <i class="fa fa-angle-left" aria-hidden="true"></i>
  </a>
  {% endif %}
  {% for num in items.paginator.page_range %}
        {% if items.number == num %}
            <span class="pagination-number pagination-current">{{ num }}</span>
        {% elif num > items.number|add:'-3' and num < items.number|add:'3' %}
            <a class="pagination-number" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
  {% if items.has_next %}
        <a class="pagination-action" href="?page={{ items.next_page_number }}">
            <i class="fa fa-angle-right" aria-hidden="true"></i>
        </a>
        <a class="pagination-action" href="?page={{ items.paginator.num_pages }}">
            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        </a>
    {% endif %}
</div>

{% endif %}




<script type='text/javascript'>
  document.getElementById('id_q').value = "{{query}}"
</script>

{% endblock %}

jobtracker/main_app/templates/main_app/job_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Job</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' job.id %}">Cancel</a>
  </form>
{% endblock %}

jobtracker/main_app/templates/main_app/job_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  
    <!-- Django requires the following for security purposes -->
    {% if object %}
    <h1><span class="edith1">{{object.position}} @ {{object.company}}</span></h1>
    {% else %}
    <h1 class='addjobh1'>Add a job to your board</h1>
    
    {% endif %}


    <form action="" method="post">
    {% csrf_token %}
    <table class="striped">
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_p }}
    </table>
    <input type="submit" value="Submit!" class="btn-add">
  </form>
  <script>
    let dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

    var selectEl = document.getElementById('id_update');
    M.FormSelect.init(selectEl);
  </script>
  
{% endblock %}